# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='child',
            field=models.CharField(default='list', max_length=20),
        ),
    ]
