# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0002_board_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='child',
            field=models.CharField(default='card', max_length=20),
        ),
    ]
